package pipeline_test

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"reflect"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"content-pipeline-insider/internal/config"
	"content-pipeline-insider/internal/mappings"
	"content-pipeline-insider/internal/pipeline"
	"content-pipeline-insider/internal/upstream"
)

// These tests need a real Postgres, and that is the point: the whole package
// is JSONB round-trips, a batch insert, and a UUID scan, none of which a fake
// would exercise honestly. Without a reachable database they skip rather than
// fail, so `go test ./...` stays green on a machine with no database running.
//
//	make migrate && go test ./internal/pipeline/...
func testRepo(t *testing.T) (*pipeline.Repository, *pgxpool.Pool) {
	t.Helper()

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("load config: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, cfg.DatabaseURL)
	if err != nil {
		t.Skipf("no database: %v", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		t.Skipf("no database at %s: %v", cfg.DatabaseURL, err)
	}
	t.Cleanup(pool.Close)

	return pipeline.NewRepository(pool), pool
}

// newPipeline creates a pipeline under a tenant id unique to this test, and
// deletes it afterwards. ON DELETE CASCADE takes the versions and mappings
// with it, so tests cannot leak rows into each other.
func newPipeline(t *testing.T, repo *pipeline.Repository, pool *pgxpool.Pool) *pipeline.Pipeline {
	t.Helper()

	tenant := uuid.New()
	p, err := repo.CreatePipeline(context.Background(), tenant, "test-"+uuid.NewString())
	if err != nil {
		t.Fatalf("CreatePipeline: %v", err)
	}

	t.Cleanup(func() {
		_, err := pool.Exec(context.Background(),
			`DELETE FROM content_pipelines WHERE tenant_id = $1`, tenant)
		if err != nil {
			t.Errorf("cleanup tenant %s: %v", tenant, err)
		}
	})
	return p
}

// sampleUpstream is deliberately not a minimal config: headers, query
// parameters, a parameter definition, authentication, and a structured body
// template all have to survive the JSONB round trip, and a config with only a
// method and URL would prove none of that.
func sampleUpstream() upstream.UpstreamConfig {
	return upstream.UpstreamConfig{
		Method:      "POST",
		URLTemplate: "https://api.partner.example/v2/products/{{productId}}",
		// The decimal and the oversized integer are here to be checked, not
		// for realism: jsonb stores numbers as numeric, and if that lost a
		// trailing zero or rounded through a float, substituteBody's
		// "249.90 must not become 249.9" guarantee would be broken by
		// storage rather than by the request builder.
		BodyTemplate: json.RawMessage(
			`{"locale":"tr-TR","include":["pricing"],"minPrice":249.90,"catalogId":9007199254740993}`),
		Headers: []upstream.Header{
			{Name: "Accept", Value: "application/json"},
		},
		QueryParameters: []upstream.QueryParam{
			{Name: "currency", Value: "TRY"},
		},
		Parameters: map[string]upstream.ParameterDef{
			"productId": {Location: upstream.ParameterLocation("path"), Required: true},
		},
		Authentication: &upstream.Authentication{
			Type:            upstream.AuthBearerToken,
			SecretReference: "tenant-45/product-api-token",
		},
		TimeoutMs: 3000,
	}
}

// sampleMappings covers every branch the repository has to encode: a required
// field, an optional one with a default, a field with no display label at all
// (NULL, not ""), and each of the four data types.
func sampleMappings() []mappings.FieldMapping {
	return []mappings.FieldMapping{
		{
			OutputName:   "productName",
			SourcePath:   "product.name",
			DataType:     mappings.TypeString,
			DisplayLabel: "Product name",
			Required:     true,
			SortOrder:    0,
		},
		{
			OutputName:   "availableStock",
			SourcePath:   "product.inventory.available",
			DataType:     mappings.TypeInteger,
			DefaultValue: json.RawMessage(`0`),
			SortOrder:    1,
		},
		{
			OutputName: "currentPrice",
			SourcePath: "product.pricing.current",
			DataType:   mappings.TypeNumber,
			Required:   true,
			SortOrder:  2,
		},
		{
			// No display label: the column must come back NULL and read as
			// an empty string, not as the literal "".
			OutputName: "inStock",
			SourcePath: "product.inStock",
			DataType:   mappings.TypeBoolean,
			SortOrder:  3,
		},
	}
}

func TestCreatePipeline(t *testing.T) {
	repo, pool := testRepo(t)

	t.Run("returns a stored row", func(t *testing.T) {
		p := newPipeline(t, repo, pool)

		if p.ID == uuid.Nil {
			t.Error("ID is nil, want one generated by the database")
		}
		if p.Status != pipeline.StatusDraft {
			t.Errorf("status = %q, want draft", p.Status)
		}
		if p.ActiveVersionID != uuid.Nil {
			t.Errorf("activeVersionID = %s, want nil until a version is published", p.ActiveVersionID)
		}
		if p.CreatedAt.IsZero() || p.UpdatedAt.IsZero() {
			t.Error("timestamps are zero, want the database defaults")
		}
	})

	t.Run("rejects a name differing only in case", func(t *testing.T) {
		p := newPipeline(t, repo, pool)

		// content_pipelines_tenant_name_idx is on lower(name): two
		// integrations in one tenant differing only in capitalisation are a
		// support ticket waiting to happen.
		_, err := repo.CreatePipeline(context.Background(), p.TenantID, upperFirst(p.Name))
		if !errors.Is(err, pipeline.ErrDuplicateName) {
			t.Fatalf("CreatePipeline = %v, want %v", err, pipeline.ErrDuplicateName)
		}
	})

	t.Run("rejects incomplete input before touching the database", func(t *testing.T) {
		if _, err := repo.CreatePipeline(context.Background(), uuid.Nil, "name"); !errors.Is(err, pipeline.ErrEmptyTenant) {
			t.Errorf("nil tenant = %v, want %v", err, pipeline.ErrEmptyTenant)
		}
		if _, err := repo.CreatePipeline(context.Background(), uuid.New(), "   "); !errors.Is(err, pipeline.ErrEmptyName) {
			t.Errorf("blank name = %v, want %v", err, pipeline.ErrEmptyName)
		}
	})
}

// TestSaveAndGetVersion is the test the whole package exists for: a recipe
// that goes into Postgres has to come back byte-identical, or a published
// version renders differently from the one that was tested.
func TestSaveAndGetVersion(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)
	ctx := context.Background()
	author := uuid.New()

	saved, err := repo.SaveDraftVersion(ctx, p.ID, author, sampleUpstream(), sampleMappings())
	if err != nil {
		t.Fatalf("SaveDraftVersion: %v", err)
	}

	if saved.VersionNumber != 1 {
		t.Errorf("version number = %d, want 1 for a pipeline's first version", saved.VersionNumber)
	}
	if saved.ID == uuid.Nil {
		t.Error("version ID is nil, want one generated by the database")
	}
	if saved.PublishedAt != nil {
		t.Errorf("publishedAt = %v, want nil for a draft", saved.PublishedAt)
	}

	loaded, err := repo.GetVersion(ctx, p.ID, 1)
	if err != nil {
		t.Fatalf("GetVersion: %v", err)
	}

	if loaded.ID != saved.ID {
		t.Errorf("id = %s, want %s", loaded.ID, saved.ID)
	}
	if loaded.CreatedBy != author {
		t.Errorf("createdBy = %s, want %s", loaded.CreatedBy, author)
	}
	if loaded.Status != pipeline.VersionDraft {
		t.Errorf("status = %q, want draft", loaded.Status)
	}

	// The upstream config survives as a document, including the structured
	// body template and the nested authentication block.
	assertUpstreamEqual(t, loaded.Upstream, sampleUpstream())

	// The mappings survive as rows, in display order.
	want := sampleMappings()
	if !reflect.DeepEqual(loaded.Mappings, want) {
		t.Errorf("mappings changed in storage:\n got %#v\nwant %#v", loaded.Mappings, want)
	}

	// Spelled out because it is the subtle half of the round trip: a missing
	// label must not come back as a non-nil empty default, and an absent
	// default must not come back as a JSON null.
	for _, m := range loaded.Mappings {
		if m.OutputName == "inStock" {
			if m.DisplayLabel != "" {
				t.Errorf("inStock label = %q, want empty", m.DisplayLabel)
			}
			if m.DefaultValue != nil {
				t.Errorf("inStock default = %s, want nil", m.DefaultValue)
			}
		}
	}
}

// TestMappingsRemainUsable closes the loop: what comes out of Postgres has to
// still drive mappings.Apply. Storing a selection that no longer transforms
// anything would be a round trip that only looks correct.
func TestMappingsRemainUsable(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)
	ctx := context.Background()

	if _, err := repo.SaveDraftVersion(ctx, p.ID, uuid.New(), sampleUpstream(), sampleMappings()); err != nil {
		t.Fatalf("SaveDraftVersion: %v", err)
	}
	loaded, err := repo.GetVersion(ctx, p.ID, 1)
	if err != nil {
		t.Fatalf("GetVersion: %v", err)
	}

	response := map[string]any{
		"product": map[string]any{
			"name":      "Kettle",
			"inventory": map[string]any{"available": json.Number("12")},
			"pricing":   map[string]any{"current": json.Number("249.90")},
			"inStock":   true,
		},
	}

	out, err := mappings.Apply(loaded.Mappings, response)
	if err != nil {
		t.Fatalf("Apply with stored mappings: %v", err)
	}

	want := map[string]any{
		"productName":    "Kettle",
		"availableStock": int64(12),
		"currentPrice":   249.90,
		"inStock":        true,
	}
	if !reflect.DeepEqual(out, want) {
		t.Errorf("Apply =\n  %#v\nwant\n  %#v", out, want)
	}
}

// TestDefaultValueFidelity pins the same integer boundary the transform tests
// pin, this time across a JSONB column: a default large enough to lose digits
// through float64 must come back exact.
func TestDefaultValueFidelity(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)
	ctx := context.Background()

	const id = 9007199254740993 // 2^53 + 1
	set := []mappings.FieldMapping{{
		OutputName:   "productId",
		SourcePath:   "product.id",
		DataType:     mappings.TypeInteger,
		DefaultValue: json.RawMessage(`9007199254740993`),
		SortOrder:    0,
	}}

	if _, err := repo.SaveDraftVersion(ctx, p.ID, uuid.New(), sampleUpstream(), set); err != nil {
		t.Fatalf("SaveDraftVersion: %v", err)
	}
	loaded, err := repo.GetVersion(ctx, p.ID, 1)
	if err != nil {
		t.Fatalf("GetVersion: %v", err)
	}

	// Applied against a response with no product.id, so the default is what
	// lands in the output.
	out, err := mappings.Apply(loaded.Mappings, map[string]any{})
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if got := out["productId"]; got != int64(id) {
		t.Errorf("productId = %v (%T), want %d", got, got, id)
	}
}

func TestVersionNumbersIncrement(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)
	ctx := context.Background()

	for want := 1; want <= 3; want++ {
		v, err := repo.SaveDraftVersion(ctx, p.ID, uuid.New(), sampleUpstream(), sampleMappings())
		if err != nil {
			t.Fatalf("SaveDraftVersion %d: %v", want, err)
		}
		if v.VersionNumber != want {
			t.Fatalf("version number = %d, want %d", v.VersionNumber, want)
		}
	}
}

func TestSaveDraftVersionErrors(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)
	ctx := context.Background()

	t.Run("unknown pipeline", func(t *testing.T) {
		// The GROUP BY in the allocation query is what makes this a
		// not-found rather than a silent version 1 against a missing row.
		_, err := repo.SaveDraftVersion(ctx, uuid.New(), uuid.New(), sampleUpstream(), sampleMappings())
		if !errors.Is(err, pipeline.ErrPipelineNotFound) {
			t.Fatalf("SaveDraftVersion = %v, want %v", err, pipeline.ErrPipelineNotFound)
		}
	})

	t.Run("empty mapping set", func(t *testing.T) {
		_, err := repo.SaveDraftVersion(ctx, p.ID, uuid.New(), sampleUpstream(), nil)
		if !errors.Is(err, mappings.ErrEmptySet) {
			t.Fatalf("SaveDraftVersion = %v, want %v", err, mappings.ErrEmptySet)
		}
	})

	t.Run("upstream with no method", func(t *testing.T) {
		cfg := sampleUpstream()
		cfg.Method = ""
		_, err := repo.SaveDraftVersion(ctx, p.ID, uuid.New(), cfg, sampleMappings())
		if !errors.Is(err, pipeline.ErrIncompleteUpstream) {
			t.Fatalf("SaveDraftVersion = %v, want %v", err, pipeline.ErrIncompleteUpstream)
		}
	})

	t.Run("no author", func(t *testing.T) {
		_, err := repo.SaveDraftVersion(ctx, p.ID, uuid.Nil, sampleUpstream(), sampleMappings())
		if !errors.Is(err, pipeline.ErrEmptyCreatedBy) {
			t.Fatalf("SaveDraftVersion = %v, want %v", err, pipeline.ErrEmptyCreatedBy)
		}
	})

	// Every rejection above happens before or during the transaction, so none
	// of them may leave a version behind. A draft that exists only because its
	// mappings failed is exactly the state the transaction prevents.
	t.Run("nothing was written", func(t *testing.T) {
		var count int
		err := pool.QueryRow(ctx,
			`SELECT count(*) FROM content_pipeline_versions WHERE pipeline_id = $1`, p.ID).Scan(&count)
		if err != nil {
			t.Fatalf("count versions: %v", err)
		}
		if count != 0 {
			t.Errorf("found %d versions after only failed saves, want 0", count)
		}
	})
}

func TestGetVersionNotFound(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)

	_, err := repo.GetVersion(context.Background(), p.ID, 7)
	if !errors.Is(err, pipeline.ErrVersionNotFound) {
		t.Fatalf("GetVersion = %v, want %v", err, pipeline.ErrVersionNotFound)
	}
}

// assertUpstreamEqual compares a stored config against the one that was
// saved, semantically rather than byte for byte.
//
// jsonb is not a text column: Postgres parses the document on the way in and
// re-serializes it on the way out, so whitespace disappears, object keys come
// back sorted, and duplicate keys are dropped. BodyTemplate is therefore never
// byte-identical after a round trip, and that is fine — substituteBody decodes
// and re-marshals it anyway, so nothing that reaches the wire depends on the
// stored bytes. What must survive is the meaning, which is what this checks.
func assertUpstreamEqual(t *testing.T, got, want upstream.UpstreamConfig) {
	t.Helper()

	if !reflect.DeepEqual(decodeJSON(t, got.BodyTemplate), decodeJSON(t, want.BodyTemplate)) {
		t.Errorf("body template changed in storage:\n got %s\nwant %s", got.BodyTemplate, want.BodyTemplate)
	}

	// Compared above; clearing the copies lets the rest be compared exactly,
	// where byte equality genuinely is the requirement.
	got.BodyTemplate, want.BodyTemplate = nil, nil
	if !reflect.DeepEqual(got, want) {
		t.Errorf("upstream config changed in storage:\n got %#v\nwant %#v", got, want)
	}
}

// decodeJSON decodes with UseNumber so numbers compare by their text. Without
// it, 249.90 and 249.9 both become float64(249.9) and the trailing zero this
// test exists to protect would be compared away.
func decodeJSON(t *testing.T, raw json.RawMessage) any {
	t.Helper()

	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()

	var v any
	if err := decoder.Decode(&v); err != nil {
		t.Fatalf("decode %s: %v", raw, err)
	}
	return v
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return string(s[0]-32) + s[1:] // ASCII-only, and these names are generated
}

func TestListRecentPipelines(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)

	if _, err := repo.SaveDraftVersion(context.Background(), p.ID, uuid.New(), sampleUpstream(), sampleMappings()); err != nil {
		t.Fatalf("SaveDraftVersion: %v", err)
	}

	list, err := repo.ListRecentPipelines(context.Background(), 50)
	if err != nil {
		t.Fatalf("ListRecentPipelines: %v", err)
	}

	var found *pipeline.PipelineSummary
	for i := range list {
		if list[i].ID == p.ID {
			found = &list[i]
			break
		}
	}
	if found == nil {
		t.Fatal("the pipeline just created is not in the listing")
	}
	if found.VersionCount != 1 || found.LatestVersion != 1 {
		t.Errorf("VersionCount=%d LatestVersion=%d, want 1 and 1", found.VersionCount, found.LatestVersion)
	}
	// Nothing is published, so the column is NULL in the database. The scan
	// must survive it rather than erroring.
	if found.ActiveVersionID != uuid.Nil {
		t.Errorf("ActiveVersionID = %s, want uuid.Nil for an unpublished pipeline", found.ActiveVersionID)
	}
}

func TestListVersions(t *testing.T) {
	repo, pool := testRepo(t)
	p := newPipeline(t, repo, pool)
	author := uuid.New()

	for i := 0; i < 2; i++ {
		if _, err := repo.SaveDraftVersion(context.Background(), p.ID, author, sampleUpstream(), sampleMappings()); err != nil {
			t.Fatalf("SaveDraftVersion %d: %v", i, err)
		}
	}

	versions, err := repo.ListVersions(context.Background(), p.ID)
	if err != nil {
		t.Fatalf("ListVersions: %v", err)
	}
	if len(versions) != 2 {
		t.Fatalf("got %d versions, want 2", len(versions))
	}
	// Newest first.
	if versions[0].VersionNumber != 2 || versions[1].VersionNumber != 1 {
		t.Errorf("version order = %d,%d, want 2,1", versions[0].VersionNumber, versions[1].VersionNumber)
	}
	if got := versions[0].FieldCount; got != len(sampleMappings()) {
		t.Errorf("FieldCount = %d, want %d", got, len(sampleMappings()))
	}
	if versions[0].PublishedAt != nil {
		t.Errorf("PublishedAt = %v, want nil for a draft", versions[0].PublishedAt)
	}
}

func TestListVersionsUnknownPipeline(t *testing.T) {
	repo, _ := testRepo(t)

	versions, err := repo.ListVersions(context.Background(), uuid.New())
	if err != nil {
		t.Fatalf("ListVersions: %v", err)
	}
	if len(versions) != 0 {
		t.Errorf("got %d versions for an unknown pipeline, want 0", len(versions))
	}
}
